import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import type { Skill } from './types.js';

const XDG_CONFIG_HOME = process.env.XDG_CONFIG_HOME || join(homedir(), '.config');
export const SHIMS_ROOT = join(XDG_CONFIG_HOME, 'easier-life-skills', 'shims');

export function shimDirFor(pluginName: string): string {
  return join(SHIMS_ROOT, pluginName);
}

export function writeShim(skill: Skill, written: Set<string>, dryRun: boolean): string {
  const dir = shimDirFor(skill.pluginName);
  if (written.has(skill.pluginName)) return dir;
  written.add(skill.pluginName);

  const file = join(dir, '.claude-plugin', 'marketplace.json');
  const content = JSON.stringify({
    name: skill.pluginName,
    owner: { name: skill.source.owner },
    description: `Synthetic marketplace shim for ${skill.source.owner}/${skill.source.repo} (plugin-only repo) — generated by @dan323/easier-life-skills`,
    plugins: [
      {
        name: skill.pluginName,
        description: `${skill.source.owner}/${skill.source.repo} (auto-shimmed)`,
        source: { source: 'url', url: skill.source.repoUrl },
      },
    ],
  }, null, 2) + '\n';

  if (dryRun) {
    console.log(`  [dry-run] would write shim ${file}`);
    return dir;
  }

  mkdirSync(join(dir, '.claude-plugin'), { recursive: true });
  const prev = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (prev !== content) writeFileSync(file, content);
  return dir;
}
